snowleopard/alga

src/Algebra/Graph/AdjacencyMap.hs
Hi,
These are some functions that I needed and didn't find.
This PR is not ready to be merged — there's no corresponding addition to IntAdjacencyMap, and the documentation is probably not up to your standards, but at least it can start a conversation.
=> Add klVertex, dfsForestFrom

src/Algebra/Graph.hs, src/Algebra/Graph/AdjacencyMap.hs, src/Algebra/Graph/Fold.hs, src/Algebra/Graph/HigherKinded/Class.hs, src/Algebra/Graph/IntAdjacencyMap.hs, src/Algebra/Graph/Relation.hs
Don't merge just yet, if you let it soak, more commits will appear :-)
=> Catch a few typos

.travis.yml
=> Add an OSX job

CHANGES.md, algebraic-graphs.cabal, src/Algebra/Graph.hs, src/Algebra/Graph/AdjacencyMap.hs, src/Algebra/Graph/Class.hs, src/Algebra/Graph/Fold.hs, src/Algebra/Graph/HigherKinded/Class.hs, src/Algebra/Graph/IntAdjacencyMap.hs, src/Algebra/Graph/NonEmpty.hs, src/Algebra/Graph/Relation.hs, test/Algebra/Graph/Test.hs, test/Algebra/Graph/Test/Arbitrary.hs, test/Algebra/Graph/Test/Fold.hs, test/Algebra/Graph/Test/Generic.hs, test/Algebra/Graph/Test/Graph.hs, test/Algebra/Graph/Test/NonEmptyGraph.hs, test/Main.hs
This is work-in-progress to address #31. I still need to fix Haddock comments and add tests.
@phadej Could you have a brief look? 
I don't particularly like the `foo1` naming convention used in `Data.List.NonEmpty`, so I'm tempted to find an alternative naming. Any suggestions?
=> WIP: Add non-empty graphs

src/Algebra/Graph/Class.hs, src/Algebra/Graph/HigherKinded/Class.hs, src/Algebra/Graph/NonEmpty.hs
Fortunately, there are not a lot of them.
=> Get rid of partial functions

src/Algebra/Graph.hs, src/Algebra/Graph/NonEmpty.hs, test/Algebra/Graph/Test/NonEmptyGraph.hs
=>  Add removeEdge to NonEmptyGraph

src/Algebra/Graph.hs, src/Algebra/Graph/Fold.hs, src/Algebra/Graph/Internal.hs, src/Algebra/Graph/NonEmpty.hs, test/Algebra/Graph/Test/NonEmptyGraph.hs
=> Final improvements to removeEdge

CHANGES.md, src/Algebra/Graph.hs, src/Algebra/Graph/AdjacencyMap.hs, src/Algebra/Graph/Fold.hs, src/Algebra/Graph/HigherKinded/Class.hs, src/Algebra/Graph/IntAdjacencyMap.hs, src/Algebra/Graph/NonEmpty.hs, src/Algebra/Graph/Relation.hs, test/Algebra/Graph/Test/Generic.hs, test/Algebra/Graph/Test/NonEmptyGraph.hs
Also add more examples and tests for `removeVertex`.
See #31.
=> Add removeVertex1 and induce1

algebraic-graphs.cabal, stack.yaml
See https://github.com/fpco/stackage/issues/3474
=> Bump QuickCheck bound

CHANGES.md, algebraic-graphs.cabal, stack.yaml
=> Prepare version 0.1.1.1

src/Algebra/Graph/Relation/Internal.hs
=> Add a NFData instance for Relation

src/Algebra/Graph.hs
Here the code for #75 
I can add some benchs if you want :)
=> Specialise overloaded functions to Graph Int

src/Algebra/Graph/NonEmpty.hs
=> Remove comment

src/Algebra/Graph/Fold.hs
As discussed in #54 
I think it also close the issue :)
=> Add NFData instance for Fold graph type

src/Algebra/Graph/Relation/InternalDerived.hs
Pretty straightforward things here.
This is related to #54 .
=> Add missing NFData instances

CHANGES.md, src/Algebra/Graph.hs, src/Algebra/Graph/AdjacencyIntMap.hs, src/Algebra/Graph/AdjacencyMap.hs, src/Algebra/Graph/Fold.hs, src/Algebra/Graph/Internal.hs, src/Algebra/Graph/NonEmpty.hs, src/Algebra/Graph/Relation.hs, src/Algebra/Graph/ToGraph.hs, test/Algebra/Graph/Test/Generic.hs
=> Optimise hasEdge, drop hasSelfLoop

CHANGES.md, src/Algebra/Graph.hs, src/Algebra/Graph/AdjacencyIntMap.hs, src/Algebra/Graph/AdjacencyIntMap/Internal.hs, src/Algebra/Graph/AdjacencyMap.hs, src/Algebra/Graph/AdjacencyMap/Internal.hs, src/Algebra/Graph/Fold.hs, src/Algebra/Graph/NonEmpty.hs, src/Algebra/Graph/Relation.hs, src/Algebra/Graph/Relation/Internal.hs, src/Algebra/Graph/ToGraph.hs, test/Algebra/Graph/Test/API.hs, test/Algebra/Graph/Test/AdjacencyIntMap.hs, test/Algebra/Graph/Test/AdjacencyMap.hs, test/Algebra/Graph/Test/Arbitrary.hs, test/Algebra/Graph/Test/Generic.hs, test/Algebra/Graph/Test/Graph.hs, test/Algebra/Graph/Test/NonEmptyGraph.hs, test/Algebra/Graph/Test/Relation.hs
See https://github.com/snowleopard/alga/issues/99#issuecomment-408714915
=> Rename fromAdjacencyList to stars

CHANGES.md, src/Algebra/Graph.hs, src/Algebra/Graph/AdjacencyIntMap.hs, src/Algebra/Graph/AdjacencyIntMap/Internal.hs, src/Algebra/Graph/AdjacencyMap.hs, src/Algebra/Graph/AdjacencyMap/Internal.hs, src/Algebra/Graph/Export.hs, src/Algebra/Graph/Export/Dot.hs, src/Algebra/Graph/NonEmpty.hs, src/Algebra/Graph/Relation.hs, src/Algebra/Graph/ToGraph.hs, test/Algebra/Graph/Test/API.hs, test/Algebra/Graph/Test/AdjacencyIntMap.hs, test/Algebra/Graph/Test/AdjacencyMap.hs, test/Algebra/Graph/Test/Generic.hs
This is work in progress in preparation for #105.
=> Extend ToGraph

algebraic-graphs.cabal
Hi,
As discussed, this add  myself as a maintainer of the `algebraic-graph` package as a "conclusion" of this GSoC !
=> Add myself as a maintainer

CHANGES.md, algebraic-graphs.cabal, src/Algebra/Graph.hs, src/Algebra/Graph/NonEmpty.hs, test/Algebra/Graph/Test/Graph.hs, test/Algebra/Graph/Test/NonEmptyGraph.hs
This adds a new function `sparsify` that will allow to efficiently process densely-connected graphs.
=> Add a draft implementation of sparsification

algebraic-graphs.cabal, src/Algebra/Graph.hs, src/Algebra/Graph/AdjacencyIntMap.hs, src/Algebra/Graph/AdjacencyMap.hs, src/Algebra/Graph/Fold.hs, src/Algebra/Graph/HigherKinded/Class.hs, src/Algebra/Graph/Label.hs, src/Algebra/Graph/Labelled.hs, src/Algebra/Graph/NonEmpty.hs, src/Algebra/Graph/Relation.hs, src/Data/Graph/Typed.hs, test/Algebra/Graph/Test/Generic.hs, test/Algebra/Graph/Test/Graph.hs, test/Algebra/Graph/Test/NonEmptyGraph.hs, test/Data/Graph/Test/Typed.hs
=> Minor revision, bump base-orphans

algebraic-graphs.cabal, src/Algebra/Graph/Labelled.hs, src/Algebra/Graph/Labelled/Example/Automaton.hs
Expanding the API of edge-labelled graphs and adding examples.
=> Further work on edge-labelled graphs

src/Algebra/Graph/Relation.hs, src/Algebra/Graph/Relation/Internal.hs
fixes #111 
Changes pass `stack test` on my machine.
=> remove setProduct, use cartesianProduct (fixes #111)

CHANGES.md, src/Algebra/Graph.hs, src/Algebra/Graph/AdjacencyIntMap.hs, src/Algebra/Graph/AdjacencyIntMap/Internal.hs, src/Algebra/Graph/AdjacencyMap.hs, src/Algebra/Graph/AdjacencyMap/Internal.hs, src/Algebra/Graph/Fold.hs, src/Algebra/Graph/Labelled.hs, src/Algebra/Graph/Labelled/AdjacencyMap.hs, src/Algebra/Graph/Labelled/AdjacencyMap/Internal.hs, src/Algebra/Graph/NonEmpty.hs, src/Algebra/Graph/Relation.hs, src/Algebra/Graph/Relation/Internal.hs, test/Algebra/Graph/Test.hs, test/Algebra/Graph/Test/Generic.hs, test/Algebra/Graph/Test/NonEmptyGraph.hs
=> Implement custom Ord instance

src/Algebra/Graph/Labelled/AdjacencyMap.hs, test/Algebra/Graph/Test/Labelled/AdjacencyMap.hs
Hello, I was playing with `LabelledAdjacencyMap` and needed this function. 
Maybe it will be useful!
=> Labelled.AdjacencyMap.replaceEdge

CHANGES.md, src/Algebra/Graph.hs, src/Algebra/Graph/AdjacencyIntMap.hs, src/Algebra/Graph/AdjacencyMap.hs, src/Algebra/Graph/HigherKinded/Class.hs, test/Algebra/Graph/Test/API.hs, test/Algebra/Graph/Test/Generic.hs, test/Algebra/Graph/Test/Graph.hs
=>  Implement relational composition of algebraic graphs

.ghci, CHANGES.md, algebraic-graphs.cabal, src/Algebra/Graph.hs, src/Algebra/Graph/AdjacencyMap.hs, src/Algebra/Graph/Class.hs, src/Algebra/Graph/Fold.hs, src/Algebra/Graph/Labelled.hs, src/Algebra/Graph/Labelled/AdjacencyMap.hs, src/Algebra/Graph/Labelled/AdjacencyMap/Internal.hs, src/Algebra/Graph/Labelled/Example/Automaton.hs, src/Algebra/Graph/Relation.hs, src/Algebra/Graph/ToGraph.hs, test/Algebra/Graph/Test/API.hs, test/Algebra/Graph/Test/Arbitrary.hs, test/Algebra/Graph/Test/Generic.hs, test/Algebra/Graph/Test/Graph.hs, test/Algebra/Graph/Test/Labelled/AdjacencyMap.hs, test/Algebra/Graph/Test/Labelled/Graph.hs, test/Algebra/Graph/Test/Relation.hs, test/Main.hs
See #17. 
This is work in progress.
=> Add documentation and tests for edge-labelled graphs

algebraic-graphs.cabal, src/Algebra/Graph/Labelled.hs
Replace CPP with a conditional `bifunctors` dependency
=> Give Graph Bifunctor on GHC 7.8 too

CHANGES.md, algebraic-graphs.cabal, src/Algebra/Graph/Class.hs, src/Algebra/Graph/Relation/Internal.hs, src/Algebra/Graph/Relation/InternalDerived.hs, src/Algebra/Graph/Relation/Symmetric.hs, src/Algebra/Graph/Relation/Symmetric/Internal.hs, src/Algebra/Graph/ToGraph.hs, test/Algebra/Graph/Test/API.hs, test/Algebra/Graph/Test/AdjacencyIntMap.hs, test/Algebra/Graph/Test/AdjacencyMap.hs, test/Algebra/Graph/Test/Generic.hs, test/Algebra/Graph/Test/Relation.hs, test/Algebra/Graph/Test/Relation/SymmetricRelation.hs
=> Symmetric relation fixes

.travis.yml, CHANGES.md, algebraic-graphs.cabal, src/Algebra/Graph/AdjacencyIntMap.hs, src/Algebra/Graph/AdjacencyIntMap/Internal.hs, src/Algebra/Graph/AdjacencyMap.hs, src/Algebra/Graph/AdjacencyMap/Internal.hs, src/Algebra/Graph/HigherKinded/Class.hs, src/Algebra/Graph/Internal.hs, src/Algebra/Graph/Label.hs, src/Algebra/Graph/Labelled/AdjacencyMap.hs, src/Algebra/Graph/Labelled/AdjacencyMap/Internal.hs, src/Algebra/Graph/Labelled/Example/Automaton.hs, src/Algebra/Graph/NonEmpty.hs, src/Algebra/Graph/Relation/Internal.hs, src/Algebra/Graph/Relation/Symmetric/Internal.hs, stack.yaml, test/Algebra/Graph/Test/Internal.hs
=> Stop supporting GHC 7.8.4

src/Algebra/Graph.hs, src/Algebra/Graph/Labelled.hs
=> Derive Generic and NFData for Algebra.Graph and Algebra.Graph.Labelled

CHANGES.md, src/Algebra/Graph/AdjacencyMap.hs, test/Algebra/Graph/Test/API.hs, test/Algebra/Graph/Test/AdjacencyIntMap.hs, test/Algebra/Graph/Test/AdjacencyMap.hs, test/Algebra/Graph/Test/Generic.hs, test/Algebra/Graph/Test/Graph.hs, test/Algebra/Graph/Test/Labelled/AdjacencyMap.hs, test/Algebra/Graph/Test/Labelled/Graph.hs, test/Algebra/Graph/Test/Relation.hs, test/Algebra/Graph/Test/Relation/SymmetricRelation.hs, test/Data/Graph/Test/Typed.hs
This required a significant revision of the testsuite, partially addressing #13.
=> Add AdjacencyMap.box

src/Algebra/Graph/AdjacencyIntMap/Algorithm.hs, src/Algebra/Graph/AdjacencyMap/Algorithm.hs
I mirrored `Data.IntMap` using `W` for `AdjacencyIntMap`s. Also, not sure why I thought the space complexity was `O(m+n)`!
Should there be any further adjustments to the documentation?
=> bfs complexity

algebraic-graphs.cabal
Following this nice blog post by @vrom911: https://vrom911.github.io/blog/common-stanzas :)
=> Reduce duplication in Cabal

src/Algebra/Graph.hs, src/Algebra/Graph/AdjacencyIntMap.hs, src/Algebra/Graph/AdjacencyMap.hs, test/Algebra/Graph/Test/RewriteRules.hs
Hi,
This PR fixes #252 
It document and test that `vertexList` and `edgeList` are good producer of lists.
=> More goodness

test/Algebra/Graph/Test/Arbitrary.hs
=> Fix compatibility with QuickCheck 2.14.2

src/Algebra/Graph.hs, src/Algebra/Graph/AdjacencyIntMap.hs, src/Algebra/Graph/AdjacencyMap.hs, src/Algebra/Graph/Bipartite/AdjacencyMap.hs, src/Algebra/Graph/Class.hs, src/Algebra/Graph/HigherKinded/Class.hs, src/Algebra/Graph/Internal.hs, src/Algebra/Graph/Label.hs, src/Algebra/Graph/Labelled.hs, src/Algebra/Graph/Labelled/AdjacencyMap.hs, src/Algebra/Graph/NonEmpty.hs, src/Algebra/Graph/NonEmpty/AdjacencyMap.hs, src/Algebra/Graph/Relation.hs, src/Algebra/Graph/Relation/Symmetric.hs, src/Algebra/Graph/Undirected.hs, test/Algebra/Graph/Test/Acyclic/AdjacencyMap.hs, test/Algebra/Graph/Test/Bipartite/AdjacencyMap.hs, test/Algebra/Graph/Test/Generic.hs
=> Clean up a few things

algebraic-graphs.cabal
=> Fix base lower bound

CHANGES.md, algebraic-graphs.cabal, hie.yaml, src/Algebra/Graph.hs, src/Algebra/Graph/AdjacencyIntMap.hs, src/Algebra/Graph/AdjacencyIntMap/Algorithm.hs, src/Algebra/Graph/AdjacencyMap.hs, src/Algebra/Graph/AdjacencyMap/Algorithm.hs, src/Algebra/Graph/Labelled.hs, src/Algebra/Graph/Labelled/AdjacencyMap.hs, src/Algebra/Graph/Labelled/Example/Automaton.hs, src/Algebra/Graph/NonEmpty.hs, src/Algebra/Graph/NonEmpty/AdjacencyMap.hs, src/Algebra/Graph/Relation.hs, src/Algebra/Graph/ToGraph.hs, src/Data/Graph/Typed.hs, stack.yaml, test/Algebra/Graph/Test/API.hs, test/Algebra/Graph/Test/Generic.hs, test/Algebra/Graph/Test/Graph.hs, test/Algebra/Graph/Test/Labelled/AdjacencyMap.hs, test/Algebra/Graph/Test/Labelled/Graph.hs, test/Algebra/Graph/Test/NonEmpty/AdjacencyMap.hs, test/Algebra/Graph/Test/NonEmpty/Graph.hs, test/Data/Graph/Test/Typed.hs
Switch to a more natural ordering of arguments. Also, make some drive-by improvements to some comments and tests.
=> Reorder algorithm arguments

src/Algebra/Graph/Example/Todo.hs
This fixes "unused OverloadedStrings" hlint error.
=> Add example todo lists, tweak formatting

.github/workflows/ci.yml, README.md
See https://github.com/badges/shields/issues/8671
=> Fix build status

algebraic-graphs.cabal
Need this to build with `ghc-9.8`.
Since its a dependency bump only, I would really appreciate a Hackage metadata edit.
=> Update deepseq dependency

algebraic-graphs.cabal
See https://github.com/commercialhaskell/stackage/issues/7391
=> Bump QuickCheck

algebraic-graphs.cabal, src/Algebra/Graph.hs, src/Algebra/Graph/AdjacencyIntMap.hs, src/Algebra/Graph/AdjacencyMap.hs, src/Algebra/Graph/AdjacencyMap/Algorithm.hs, src/Algebra/Graph/Class.hs, src/Algebra/Graph/HigherKinded/Class.hs, src/Algebra/Graph/Relation.hs, src/Algebra/Graph/Relation/Symmetric.hs
This required minor changes to avoid conflicting with `Data.Tree.edges`.
=> Support containers 0.8
