snowleopard/alga

- CHANGES.md
- src/Algebra/Graph.hs
- src/Algebra/Graph/AdjacencyMap.hs
- src/Algebra/Graph/AdjacencyMap/Internal.hs
- src/Algebra/Graph/Class.hs
- src/Algebra/Graph/Fold.hs
- src/Algebra/Graph/HigherKinded/Class.hs
- src/Algebra/Graph/IntAdjacencyMap.hs
- src/Algebra/Graph/IntAdjacencyMap/Internal.hs
- src/Algebra/Graph/Relation.hs
- src/Algebra/Graph/Relation/Internal.hs
- test/Algebra/Graph/Test/API.hs
- test/Algebra/Graph/Test/Generic.hs
After using the library for a while I think we can drop the smart constructor `graph` for the following reasons:
* It's very rarely needed and it's easy to implement via `overlay` if need be.
* It's awkward, because it brings us back to the `(V,E)` definition of graphs and can lead to a confusion between `graph [1] [(1, 2)]` and `graph [1, 2] [(1, 2)]`. 
* It takes up a useful name `graph`.
* It's one extra function to maintain, test and document.
> Remove smart constructor 'graph'

- CHANGES.md
- algebraic-graphs.cabal
- src/Algebra/Graph/Export.hs
- src/Algebra/Graph/Utilities.hs
- test/Algebra/Graph/Test/Export.hs
- test/Algebra/Graph/Test/Utilities.hs
- test/Main.hs
Difference lists are often useful, so it makes sense to factor them out into a separate module.
> Factor out Doc into Algebra.Graph.Utilities

- CHANGES.md
- algebraic-graphs.cabal
- src/Algebra/Graph/Export.hs
- src/Algebra/Graph/Internal.hs
- src/Algebra/Graph/Utilities.hs
- test/Algebra/Graph/Test/Export.hs
- test/Algebra/Graph/Test/Internal.hs
- test/Algebra/Graph/Test/Utilities.hs
- test/Main.hs
We should really split difference lists `List a` whose semantics is a list of elements from documents `Doc a` whose semantics is a single concatenated string (the contents). Mixing these notions leads to surprises.
TODO: update documentation and tests.
> Split difference lists from documents

- src/Algebra/Graph/NonEmpty.hs
- test/Algebra/Graph/Test/NonEmptyGraph.hs
Export `toNonEmptyGraph` and `overlay1` functions implemented as part of #43.
> Extend Algebra.Graph.NonEmpty API

- algebraic-graphs.cabal
A revision, or new release would be great! 
Note: PVP says next version can be `0.1.1.1`, as first three digits stays the same we "communicate" that there are no publicly visible changes in the API - which makes update a no-brainer. FWIW, 0.1.1 could been `0.1.0.1` - I was a little disappointed as there weren't "new features" in 0.1.1 :( - That said, it's not wrong, it's only not as semantically precise as it could be. I'm confused by those things myself.
> Allow base-compat-0.10

- src/Algebra/Graph.hs
Using the set alternative is a bit quicker and use la bit less memory :)
Benchmarks:
```
+----------------------------++-----------------------+
|                            ||        Seconds (Mean) |
+============================++=======================+
| SetBasedOp (Algebra.Graph) ||  7.292685126584078e-8 |
|       Alga (Algebra.Graph) || 1.8151521274477894e-7 |
+----------------------------++-----------------------+
+----------------------------++-----------------------+
|                            ||        Seconds (Mean) |
+============================++=======================+
| SetBasedOp (Algebra.Graph) || 1.4376476714566372e-6 |
|       Alga (Algebra.Graph) ||  2.637610519434279e-6 |
+----------------------------++-----------------------+ …
```
> Replace vertexCount by its Set.size alternative

- src/Algebra/Graph/AdjacencyMap.hs
- test/Algebra/Graph/Test/API.hs
- test/Algebra/Graph/Test/AdjacencyMap.hs
- test/Algebra/Graph/Test/Generic.hs
The actual implementation of `edges` for `AdjacencyMap` used two successive `map`. Here is a reduced version :)
> concat two map for edges

- algebraic-graphs.cabal
- src/Algebra/Graph/AdjacencyMap.hs
- src/Algebra/Graph/AdjacencyMap/Internal.hs
- src/Algebra/Graph/IntAdjacencyMap.hs
- src/Algebra/Graph/IntAdjacencyMap/Internal.hs
- src/Algebra/Graph/KingLaunchbury.hs
- src/Data/Graph/Typed.hs
- test/Algebra/Graph/Test/AdjacencyMap.hs
- test/Algebra/Graph/Test/IntAdjacencyMap.hs
- test/Data/Graph/Test/Typed.hs
- test/Main.hs
This removes the `graphKL` field from `AdjacencyMap` as suggested in #54 and makes the `GraphKL` data type publicly available in `Algebra.Graph.KingLaunchbury` instead (similar to the proposal in #24). Changes:
- Remove `graphKL` and `mkAM` from `AdjacencyMap`
- Replace `dfs`, `topSort` and `scc` with slightly slower versions operating on pure `AdjacencyMap`s
- Move the old ones into `Algebra.Graph.KingLaunchbury` and make them (largely) independent of `AdjacencyMap`
Not changed (yet):
- The `graphKL` field and algorithms of `IntAdjacencyMap`
- No `Graph a -> GraphKL a` conversion yet.
- Comments are a mess.
The benefit of this is that the original behaviour of the API can still be recovered by just manually converting to the `GraphKL` type, while the unexpected behaviour of `dfs`, ... is …
> Draft for extracting King-Launchbury graphs from AdjacencyMap

- src/Algebra/Graph/AdjacencyMap/Internal.hs
- src/Algebra/Graph/IntAdjacencyMap/Internal.hs
Finally with the great work of @anfelor ,  a clear instance of `NFData` for `AdjacencyMap` is emerging.
This is obviously related to #54
> NFData for AdjacencyMap

- src/Algebra/Graph.hs
- src/Algebra/Graph/ToGraph.hs
Related to #75 
Please note that the speeded-up Eq instance needed some tweaks as described [here](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/glasgow_exts.html#how-rules-interact-with-class-methods)
The benchs:
Descritpion: Produce a list of the vertices in the graph
<TABLE>
<TR>
<TH>
</TH>
<TH CLASS = "thinright">
1
</TH>
<TH CLASS = "thinright">
10
</TH>
<TH CLASS = "thinright">
100
</TH>
<TH>
1000
</TH>
</TR>
<TR>
<TH>
Alga
</TH>
<TD CLASS = "thinright">
45.11 ns
</TD>
<TD CLASS = "thinright">
1.722 μs
</TD>
<TD CLASS = "thinright">
359.0 μs
</TD>
<TD>
85.77 ms
</TD>
</TR>
<TR>
<TH>
AlgaOld
</TH>
<TD CLASS = "thinright">
44.79 ns
</TD>
<TD CLASS = "thinright">
17.41 μs
</TD>
<TD CLASS = "thinright">
3.755 ms
</TD>
<TD>
604.7 ms
</TD>
</TR>
</TABLE>
<TABLE>
<TR> …
> Graph int speedup

- .travis.yml
Hi,
As you requested, here is the .travis.yml updated to bench alga against an older version of itself.
It basically calls a script I made here: https://github.com/nobrakal/benchAlgaPr/blob/master/compare.sh
It is (very) tricky, here is some explanation:
This script will clone alga, and reset it to `HEAD^1" if it is a direct push, or leave it as "HEAD" if it is a PR (so PR will be benchmarked against HEAD, and direct push against HEAD^1). (The script itself can be parametrized to use an other commit id)
Then I rename the algebraic-graph package to "old", renaming the "Algebra.Graph" module to "Algebra.GraphOld".
Then it will clone and modify https://github.com/haskell-perf/graphs/ to match this.
And then it will run the benchmarks.
I disabled the output, so only the ABSTRACT and SUMMARY …
> Bench on commit

- .travis.yml
Hi,
I have updated the script to support the benchmarks of NonEmpty graphs and created two Travis jobs dedicated to the benchmark of the `Algebra.Graph` and `Algebra.Graph.NonEmpty` module.
The tricky part is that the benchmark suite need criterion which need many dependencies. I needed to set a timeout for the action, so it fail before the Travis time limit and allow caching these dependencies (if the time limit is reached, the is no caching).
So if the build first fail, it certainly due to benchamrks dependencies, so re-run it and, as they have been cached, the build should pass.
Example here: https://travis-ci.com/nobrakal/alga/builds/78616254
> Add regression suite for NonEmpty and update current one

- src/Algebra/Graph.hs
Hi,
Trying to improve the `MaybeNonEmpty` version, I discovered that the rewrite rules are very powerful for `edgeList` (it comes from the quickness of AdjacencyIntMap):
Description: Produce a list of the edges in the graph
<TABLE>
<TR>
<TH>
</TH>
<TH>
100
</TH>
</TR>
<TR>
<TH>
Alga
</TH>
<TD>
77.91 μs
</TD>
</TR>
<TR>
<TH>
AlgaOld
</TH>
<TD>
206.3 μs
</TD>
</TR>
</TABLE>
<TABLE>
<TR>
<TH>
</TH>
<TH>
100
</TH>
</TR>
<TR>
<TH>
Alga
</TH>
<TD>
2.347 ms
</TD>
</TR>
<TR>
<TH>
AlgaOld
</TH>
<TD>
7.619 ms
</TD>
</TR>
</TABLE>
<TABLE>
<TR>
<TH>
</TH>
<TH>
100
</TH>
</TR>
<TR>
<TH>
Alga
</TH>
<TD>
39.63 μs
</TD>
</TR>
<TR>
<TH>
AlgaOld
</TH>
<TD>
118.9 μs
</TD>
</TR>
</TABLE>
SUMMARY:
* Alga was the fastest 3 times
ABSTRACT:
(Based on an average of the ratio between largest benchmarks)
* Alga was …
> Use rewrite rules instead of some specialization

- src/Algebra/Graph/NonEmpty.hs
Hi,
As discussed in #93 , here are several optimizations to `Algebra.Graph.NonEmpty`.
Mainly with:
* `SPECIALIZE` pragma when possible and useful
* `RULES` when possible and useful
* Previous improvements founds while working on #90
The benchmarks:
```
vertexList1: 0.08 (good)
vertexCount: 0.07 (good)
hasVertex: 3.71 (bad)
edgeCount: 0.36 (good)
edgeList: 0.37 (good)
hasEdge: 0.25 (good)
hasSelfLoop: 1.02 (OK)
addEdge: 1.00 (OK)
addVertex: 1.02 (OK)
removeVertex1: 1.01 (OK)
equality: 0.34 (good)
removeEdge: 0.96 (OK)
transpose: 1.00 (OK)
dff: 1.01 (OK)
topSort: 1.01 (OK)
edges1: 0.83 (good)
``` 
So everything is green, the drop of `hasVertex` as already been documented here: https://github.com/snowleopard/alga/issues/90#issuecomment-403087848
> NonEmpty graphs optimizations

- src/Algebra/Graph.hs
- src/Algebra/Graph/Fold.hs
- src/Algebra/Graph/NonEmpty.hs
Hi,
I have played again a bit, but I think I have found a better one this time :)
The boost come from two things:
1. The first one, I had never checked it, but `induce (\x -> elem x [u,v])` was not a great idea. Just replacing it by `induce (\x -> x == u || x == v)` is clearly a better idea:
<TABLE>
<TR>
<TH>
</TH>
<TH>
1000
</TH>
</TR>
<TR>
<TH>
WithEq
</TH>
<TD>
70.80 ms
</TD>
</TR>
<TR>
<TH>
WithElem
</TH>
<TD>
103.4 ms
</TD>
</TR>
</TABLE>
2. Then, because the equality test was already done in the "induce", I had the idea to store it and pass it to a modified version from `ToGraph`:
```Haskell
hasEdge :: Eq a => a -> a -> Graph a -> Bool
hasEdge s t = hasEdge' . induce'
where
hasEdge' g = case foldg e v o c g of (_, _, r) -> r
where
e                             = (False   , False   , …
```
> Better hasEdge for Algrebra.Graph

- .travis.yml
- CHANGES.md
- src/Algebra/Graph/AdjacencyIntMap.hs
- src/Algebra/Graph/AdjacencyMap.hs
- src/Algebra/Graph/ToGraph.hs
- test/Algebra/Graph/Test/AdjacencyIntMap.hs
- test/Algebra/Graph/Test/AdjacencyMap.hs
- test/Algebra/Graph/Test/Generic.hs
- test/Main.hs
This is useful for testing the existing implementation of DFS, but will become even more useful when adding new DFS implementations based on algebraic graph representations.
> Add a function to check the correctness of depth-first search

- CHANGES.md
- src/Algebra/Graph.hs
- src/Algebra/Graph/Fold.hs
- src/Algebra/Graph/HigherKinded/Class.hs
- src/Algebra/Graph/Labelled.hs
- src/Algebra/Graph/NonEmpty.hs
- src/Algebra/Graph/ToGraph.hs
- test/Algebra/Graph/Test/API.hs
This is related to #95 
So:
* It removes `Foldable` and `Traversable` instance from concerned Graph data-types.
* It removes comments related to `Foldable` instances.
* It drops `isEmpty`, `hasVertex`, `vertexCount`, `vertexList`, `vertexSet`, `vertexIntSet` and `box` from `Algebra.Graph.HigherKinded.Class` because of the removal of the `Foldable` constraint. `mesh` and ` torus` were rewrited without `box`.
* I don't really know what is happening in `Algebra.Graph.Labelled` but I had to add a `foldgUnDiff` and a real `hasVertex` (because `elem` was used previously).
* I added a comment related to the `Foldable` instance in `Algebra.Graph.ToGraph` (I don't know if it is in the right module).
> Remove foldable

- .travis.yml
- CHANGES.md
- algebraic-graphs.cabal
- stack.yaml
I've bumped the next version to `0.3` since we are breaking API, updated change log, and LTS version.
Also, I've switched the performance regression suite to GHC 8.6.1.
> Various updates: bump version and LTS, update change log and CI

- CHANGES.md
- algebraic-graphs.cabal
- src/Algebra/Graph/AdjacencyIntMap.hs
- src/Algebra/Graph/AdjacencyIntMap/Algorithm.hs
- src/Algebra/Graph/AdjacencyIntMap/Internal.hs
- src/Algebra/Graph/AdjacencyMap.hs
- src/Algebra/Graph/AdjacencyMap/Algorithm.hs
- src/Algebra/Graph/AdjacencyMap/Internal.hs
- src/Algebra/Graph/NonEmpty/AdjacencyMap.hs
- src/Algebra/Graph/NonEmpty/AdjacencyMap/Internal.hs
- src/Algebra/Graph/ToGraph.hs
- src/Data/Graph/Typed.hs
- test/Algebra/Graph/Test/API.hs
- test/Algebra/Graph/Test/AdjacencyMap.hs
- test/Algebra/Graph/Test/Generic.hs
See #128.
The draft implementation seems to work correctly, but I need to add tests and documentation.
For example, given a graph `edges [(1,2), (2,3), (3,4), (4,3), (2,1)]`, the new `scc` finds a graph with two vertices `1*2 + 2*1` and `3*4 + 4*3` of type `NonEmptyGraph Int` and one edge between them.
Before merging this PR, I will need to address #126 (since we need an `Ord` instance for `NonEmptyGraph`s to store them inside an `AdjacencyMap`).
> Add a draft implementation of new SCC algorithm

- src/Algebra/Graph/AdjacencyIntMap/Internal.hs
- src/Algebra/Graph/AdjacencyMap/Internal.hs
- src/Algebra/Graph/Fold.hs
- src/Algebra/Graph/Labelled/AdjacencyMap/Internal.hs
- src/Algebra/Graph/NonEmpty/AdjacencyMap/Internal.hs
- src/Algebra/Graph/Relation/Internal.hs
- test/Algebra/Graph/Test/Generic.hs
- test/Algebra/Graph/Test/NonEmpty/AdjacencyMap.hs
This should fix the starter bug #140.
Not quite all `show` code paths get tested with the updated unit tests; notably `Labelled.AdjacencyMap` remains with no tests.
> Fix Show instances to insert parens (#140)

- .ghci
- .ghcid
- .gitignore
@nobrakal I propose to change our `ghcid` setup: instead of using the `.ghcid` file, we'll use `.ghci` instead. This seems to be faster in the sense that we don't need to compile with optimisation.
As a drawback, I think the rewrite rules are no longer tested automatically.
> Replace .ghcid with .ghci

- src/Algebra/Graph.hs
- test/Algebra/Graph/Test/RewriteRules.hs
Hi there,
I have:
* implemented the deforestation rules for `bind`
* rewritten `fmap` in term of `bind`
* added a test to verify that `fmap f . fmap g` was rewritten in `fmap (f.g)`
Happy Holidays :)
> Rewrite Rules for bind

- src/Algebra/Graph.hs
- src/Algebra/Graph/NonEmpty.hs
Re-implement Cartesian graph product `box` using Applicative instance, which allows to preserve the shape of original expressions to some degree (instead of flattening expression trees using `overlays`).
> Switch to Applicative-based Cartesian graph product

- src/Algebra/Graph.hs
- src/Algebra/Graph/NonEmpty.hs
Hi,
I just saw that in the actual `isSubGraphOf`, the second argument was converted two times in the same adjacency map in `Algebra.Graph{,.NonEmpty}`.
This PR solves this by introducing a variable. Note that the code is a bit less clear and I had to add specialized functions by hand (since I use directly `overlay` from `AdjacencyMap` or `AdjacencyIntMap` ).
> Speedup for isSubgraphOf

- src/Algebra/Graph.hs
- src/Algebra/Graph/NonEmpty.hs
- test/Algebra/Graph/Test/RewriteRules.hs
Hi there,
This only change the definition of `(<*>)` in `Algebra.Graph` to an equivalent made with `bindR` (suggested by @snowleopard  ), which allow fusion with compatible functions.
> Make (<*>) subject to fusion

- src/Algebra/Graph/Labelled.hs
I was looking for simple contributions to give to an Haskell project and I found #156, so I have given it a go. This is my first [multi character](https://github.com/supki/ldap-client/commit/824b44ac22eb68d734500e5378e2be50f315fefb) contribution in Haskell so any kind of comments or suggestions are welcome  :-)
Also let me know if this corresponds to what you had in mind.
> Add bifunctor instance for labelled graphs

- test/Algebra/Graph/Test/Arbitrary.hs
This addresses issue #150.
Nothing very smart here, I consider graphs with one less vertex and one less edge. Tests pass but I haven't managed to reproduce an existing bug to see if counterexamples would get smaller.
> Implement custom shrinking for AdjacencyMap and AdjancencyIntMap

- CHANGES.md
- algebraic-graphs.cabal
- stack.yaml
See https://github.com/commercialhaskell/stackage/issues/4444
> Bump LTS and allow newer QuickCheck

- .travis.yml
Hi,
These commits fix the benchmarking suite. The fail was due to the changes made in `.travis.yml`.
I changed accordingly the script in my repository ( https://github.com/nobrakal/benchAlgaPr ), don't hesitate to pull if you use it locally :)
> Fix the benchmarking suite

- algebraic-graphs.cabal
Looks like `inspection-testing-0.4.2` breaks our tests for rewrite rules, so I will disallow it for now.
> Disallow inspection-testing 0.4.2

- AUTHORS.md
- src/Algebra/Graph.hs
- src/Algebra/Graph/AdjacencyMap.hs
- src/Algebra/Graph/Labelled.hs
- src/Algebra/Graph/Labelled/AdjacencyMap.hs
- src/Algebra/Graph/NonEmpty.hs
- src/Algebra/Graph/NonEmpty/AdjacencyMap.hs
- src/Algebra/Graph/Relation.hs
- src/Algebra/Graph/Relation/Symmetric.hs
- test/Algebra/Graph/Test/API.hs
- test/Algebra/Graph/Test/AdjacencyMap.hs
- test/Algebra/Graph/Test/Generic.hs
- test/Algebra/Graph/Test/Graph.hs
- test/Algebra/Graph/Test/Labelled/AdjacencyMap.hs
- test/Algebra/Graph/Test/Labelled/Graph.hs
- test/Algebra/Graph/Test/NonEmpty/AdjacencyMap.hs
- test/Algebra/Graph/Test/NonEmpty/Graph.hs
- test/Algebra/Graph/Test/Relation.hs
- test/Algebra/Graph/Test/Relation/SymmetricRelation.hs
> Add induceJust

- CHANGES.md
- src/Algebra/Graph.hs
- src/Algebra/Graph/AdjacencyMap.hs
- src/Algebra/Graph/Labelled.hs
- src/Algebra/Graph/Labelled/AdjacencyMap.hs
- src/Algebra/Graph/NonEmpty.hs
- src/Algebra/Graph/NonEmpty/AdjacencyMap.hs
- src/Algebra/Graph/Relation.hs
- src/Algebra/Graph/Relation/Symmetric.hs
- test/Algebra/Graph/Test/Generic.hs
- test/Algebra/Graph/Test/NonEmpty/AdjacencyMap.hs
- test/Algebra/Graph/Test/NonEmpty/Graph.hs
> Revise documentation and tests for induceJust

- CHANGES.md
- algebraic-graphs.cabal
- src/Algebra/Graph/Acyclic/AdjacencyMap.hs
- src/Algebra/Graph/Acyclic/AdjacencyMap/Ord.hs
- src/Algebra/Graph/AdjacencyIntMap.hs
- src/Algebra/Graph/AdjacencyMap.hs
- src/Algebra/Graph/Label.hs
- src/Algebra/Graph/Labelled/AdjacencyMap.hs
- test/Algebra/Graph/Test/Acyclic/AdjacencyMap.hs
- test/Algebra/Graph/Test/Arbitrary.hs
- test/Algebra/Graph/Test/Generic.hs
- test/Main.hs
This PR includes:
* A lot of changes to comments, examples, implementation and tests.
* Renaming `disjointOverlay` to `union` and `disjointConnect` to `join`, which are commonly used terms.
* Adding some missing functions: `isSubgraphOf`, `preSet`, `postSet`.
* Removal of `PartialOrder`: I'm still hesitating about providing an unsafe construction method.
* Moving `Acyclic.Ord` to `Acyclic.AdjacencyMap.Ord`, and removing some functions from the API.
> Revise Acyclic.AdjacencyMap

- src/Algebra/Graph/Label.hs
Minor change: Removed `Num` constraint on `Show` for `Minimum` in `Algebra.Graph.Label`
> Removed unecessary condition

- src/Algebra/Graph/Acyclic/AdjacencyMap.hs
- src/Algebra/Graph/AdjacencyIntMap/Algorithm.hs
- src/Algebra/Graph/AdjacencyMap/Algorithm.hs
- src/Algebra/Graph/ToGraph.hs
- test/Algebra/Graph/Test/API.hs
- test/Algebra/Graph/Test/Acyclic/AdjacencyMap.hs
- test/Algebra/Graph/Test/Generic.hs
I threw together the monadic tree unfold version.
I also tried doing top sort directly, since I think it could be advantageous to build the final list directly without going through a forest structure first. It should also allow an early exit if a back edge is detected.
> improve dfs & top sort performance

- algebraic-graphs.cabal
- stack.yaml
- test/Algebra/Graph/Test/RewriteRules.hs
The rewrite tests are tricky. Giving `inspection-testing` a stricter lower bound fixes one issue, but introduces another.
> GHC 8.8 support

- src/Algebra/Graph/Undirected.hs
- test/Algebra/Graph/Test/Undirected.hs
Regarding the [last tests](https://github.com/gabrielelana/alga/blob/undirected-complement/test/Algebra/Graph/Test/Undirected.hs#L83) we don't know if it's ok for Arbitrary to generate graphs with loops
Fixes #21
Proudly made by @sphaso and @gabrielelana at "Open Source Saturday Milano"
[![Open Source Saturday](https://img.shields.io/badge/%E2%9D%A4%EF%B8%8F-open%20source%20saturday-F64060.svg)](https://www.meetup.com/it-IT/Open-Source-Saturday-Milano/)
> Implement complement for undirected graphs

- src/Algebra/Graph/NonEmpty.hs
There is an intention to stop re-exporting functions from `base` in future versions of `mtl`: https://github.com/haskell/mtl/pull/74
This PR brings `alga` in line with the proposed change, because at the moment `Algebra.Graph.NonEmpty` imports `liftM2` (originally from `Control.Monad`) from `Control.Monad.State`.
> Import liftM2 from Control.Monad instead of Control.Monad.State

- src/Algebra/Graph.hs
- src/Algebra/Graph/Labelled.hs
- src/Algebra/Graph/NonEmpty.hs
- src/Algebra/Graph/NonEmpty/AdjacencyMap.hs
- src/Algebra/Graph/Undirected.hs
Implementing `induce` as `induce p = induceJust . fmap (\a -> if p a then Just a else Nothing)` seems to pass inspection tests. My understanding is that this means `fmap` fuses nicely with the `induceJust`, and so using this simpler definition comes at no runtime cost.
@nobrakal Could you have a look?
> Implement induce via induceJust

- src/Algebra/Graph/Export/Dot.hs
- test/Algebra/Graph/Test/Export.hs
GraphViz supports different types of label. The type is determined by
the delimiters used to quote the label's value. Double-quotes denote
a literal string. Pairs of angle brackets ("<>") denote a "HTML-like"
string, which permits the use of (some) HTML mark-up in the graph.
Extend the `Style` record type to include a `quoting` field, to signal
whether or not attribute values should be double-quoted. A user wishing
to use another quote style must define their style's quoting attribute
as `NoQuote` and then ensure their attribute values contain embedded
quote characters of their choice.
Adjust `defaultStyle` and the `attributes` function accordingly and add
a test.
Fixes #272.
----
[Here's an example of the above in use](https://github.com/jmtd/striot/commit/38ee592c7f4cea4b695c6db5a94fe852 …
> Export.Dot: Extend Style to define Quoting styles

- .github/workflows/ci.yml
- CHANGES.md
- algebraic-graphs.cabal
- src/Algebra/Graph.hs
- src/Algebra/Graph/Export.hs
- src/Algebra/Graph/Internal.hs
- src/Algebra/Graph/Label.hs
- src/Algebra/Graph/NonEmpty.hs
- test/Algebra/Graph/Test/Arbitrary.hs
- test/Algebra/Graph/Test/Export.hs
- test/Algebra/Graph/Test/Internal.hs
- test/Algebra/Graph/Test/Labelled/AdjacencyMap.hs
- test/Algebra/Graph/Test/Labelled/Graph.hs
- test/Algebra/Graph/Test/NonEmpty/AdjacencyMap.hs
- test/Algebra/Graph/Test/NonEmpty/Graph.hs
> Stop supporting GHC 8.0 and 8.2

- algebraic-graphs.cabal
- src/Algebra/Graph/Example/Todo.hs
- test/Algebra/Graph/Test/Example/Todo.hs
- test/Main.hs
Per suggestions in #51:
- Resolve namespace conflict between 'AdjacencyGraph' and 'Class'
- Ignore cycles after topSort in `todo`
> Recover previous Todo example

- CHANGES.md
- src/Algebra/Graph/Labelled.hs
- src/Algebra/Graph/Labelled/AdjacencyMap.hs
- src/Algebra/Graph/Relation.hs
- src/Algebra/Graph/Relation/Symmetric.hs
- src/Algebra/Graph/ToGraph.hs
- src/Algebra/Graph/Undirected.hs
A few changes related to `ToGraph`:
* Move as many instances as possible from the `ToGraph` module to the modules where the data types are actually defined.
* Fix symmetric `Relation` instance, and move it to `Algebra.Graph.Relation.Symmetric`.
> Revise ToGraph

- src/Algebra/Graph/Label.hs
Add smart constructors for Symbol , with the long-term goal of deprecating the IsList instance.  
I should note in passing that the GHC  DEPRECATE pragma doesn't work with class instances, which leaves the fix up to a judicious versioning schedule
Addresses (partly) #297
> add symbol, symbols
